### PR TITLE
minor spelling and grammar

### PR DESCRIPTION
**Pull request by SeeThruHead**

### CODE REVIEW

**Comment by slashfoo** [comment]
https://github.com/caiorss/Functional-Programming/pull/1/files#diff-04c6e90faac2675aa89e2176d2eec7d8R160

:browse vs :browser, no?

**Comment by tkovs** [comment]
/\ Yeah. :browse

**Comment by SeeThruHead** [comment]
fixed browse but can't squash due to helloworld.hs and HelloWorld.hs causing a modification on OSX. Not sure what the workaround is for that.

**Comment by caiorss** [comment]
Fixed. From :browser to :browse in README.md

**Pull request closed without merging**
